# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xa7a15tcpg236-2I

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /media/Data/Work/adder_tb_vivado/xapp/vcs_project/spectrum_vv/spectrum_vv.cache/wt [current_project]
set_property parent.project_path /media/Data/Work/adder_tb_vivado/xapp/vcs_project/spectrum_vv/spectrum_vv.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files /media/Data/Work/adder_tb_vivado/xapp/vcs_ip_location/coeffs/fir_p2_1db_s3_50db.coe
read_verilog -library xil_defaultlib /media/Data/Work/adder_tb_vivado/xapp/vcs_project/src/verilog/spectrum_top.v
read_vhdl -library xil_defaultlib /media/Data/Work/adder_tb_vivado/xapp/vcs_project/src/vhdl/heartbeat_gen.vhd
synth_design -top spectrum_top -part xa7a15tcpg236-2I
write_checkpoint -noxdef spectrum_top.dcp
catch { report_utilization -file spectrum_top_utilization_synth.rpt -pb spectrum_top_utilization_synth.pb }
