# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /media/Data/Work/adder_tb_vivado/Adder/Adder.cache/wt [current_project]
set_property parent.project_path /media/Data/Work/adder_tb_vivado/Adder/Adder.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zc702:part0:1.2 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib /media/Data/Work/adder_tb_vivado/Adder/Adder.srcs/sources_1/new/add.v
synth_design -top add -part xc7z020clg484-1
write_checkpoint -noxdef add.dcp
catch { report_utilization -file add_utilization_synth.rpt -pb add_utilization_synth.pb }
