webtalk_init -webtalk_dir /media/Data/Work/adder_tb_vivado/xapp/vcs_project/spectrum_vv/spectrum_vv.sim/sim_1/behav/xsim.dir/spectrum_top_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Mar  2 17:53:51 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2015.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1368829" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211010112_0_0_832" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "e1823266ebfd5579a1ede4b6ba9eff6d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2a3b93df4da84d73be0784ab06f51722" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 14.04.3 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "800.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.02_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "257408_KB" -context "xsim\\usage"
webtalk_transmit -clientid 52382648 -regid "211010112_0_0_832" -xml /media/Data/Work/adder_tb_vivado/xapp/vcs_project/spectrum_vv/spectrum_vv.sim/sim_1/behav/xsim.dir/spectrum_top_behav/webtalk/usage_statistics_ext_xsim.xml -html /media/Data/Work/adder_tb_vivado/xapp/vcs_project/spectrum_vv/spectrum_vv.sim/sim_1/behav/xsim.dir/spectrum_top_behav/webtalk/usage_statistics_ext_xsim.html -wdm /media/Data/Work/adder_tb_vivado/xapp/vcs_project/spectrum_vv/spectrum_vv.sim/sim_1/behav/xsim.dir/spectrum_top_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
